version: '3'
services:
  database:
    image: postgres:14
    container_name: database
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]

  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    environment:
      - HOST=database
      - PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    
  backend-migrations:
    build: .
    env_file:
      - .env
    environment:
      - HOST=database
      - PORT=5432
    command: bash -c "make migrate"
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started

  backend-superuser:
    build: .
    env_file:
      - .env
    environment:
      - HOST=database
      - PORT=5432
    command: bash -c "make create-superuser"
    depends_on:
      database:
        condition: service_healthy
      backend-migrations:
        condition: service_started
      backend:
        condition: service_started

volumes:
  pg_data: