version: '3'
services:
  database:
    image: postgres:14
    container_name: database
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - web_net
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - HOST=database
      - PORT=5432
    ports:
      - "8000:8000"
    networks:
      - web_net
    depends_on:
      - database

networks:
  web_net:
    driver: bridge

volumes:
  pg_data: