# Generated by Django 4.2.6 on 2023-10-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('group_number', models.IntegerField()),
                ('last_name', models.CharField(max_length=255)),
                ('prof_cum_ticketNumber', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('telegram_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('current_query_id', models.BigIntegerField()),
            ],
        ),
    ]
