# Generated by Django 4.2.6 on 2023-11-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], default='monday', max_length=9)),
                ('office', models.CharField(choices=[(1, 'Большая морская 67'), (2, 'Ленсовета 14'), (3, 'Гастелло 14')], default=1, max_length=40)),
                ('start_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
    ]
