# Generated by Django 4.2.6 on 2023-11-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_number',
            field=models.CharField(max_length=10, verbose_name='Номер группы'),
        ),
    ]
