# Generated by Django 4.2.6 on 2023-11-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_query_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='query',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_query_id',
            field=models.BigIntegerField(verbose_name='Текущий номер запроса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_number',
            field=models.IntegerField(verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(verbose_name='Телеграмм ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ticket_number',
            field=models.CharField(max_length=255, verbose_name='Номер профкома'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
