# Generated by Django 4.2.6 on 2023-11-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_workingday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingday',
            options={'verbose_name': 'Рабочий день', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AlterField(
            model_name='workingday',
            name='close_time',
            field=models.TimeField(verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], default='monday', max_length=9, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='office',
            field=models.IntegerField(choices=[(1, 'Большая морская 67'), (2, 'Ленсовета 14'), (3, 'Гастелло 14')], default=1, verbose_name='Адрес профкома'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='start_time',
            field=models.TimeField(verbose_name='Начало работы'),
        ),
    ]
