# Generated by Django 4.2.6 on 2023-11-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_workingday_options_alter_workingday_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='day_of_week',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default='monday', max_length=15, verbose_name='День недели'),
        ),
    ]
